# Generated by Django 4.2.6 on 2023-11-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contact_contactforms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactforms',
            options={'verbose_name_plural': 'contact forms'},
        ),
    ]
