# Generated by Django 4.2.6 on 2023-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('genres', models.TextField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('production_companies', models.CharField(blank=True, max_length=200, null=True)),
                ('production_countries', models.CharField(blank=True, max_length=200, null=True)),
                ('spoken_languages', models.CharField(blank=True, max_length=200, null=True)),
                ('original_language', models.CharField(blank=True, max_length=200, null=True)),
                ('original_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
