# Generated by Django 4.2.6 on 2023-11-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comment_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
    ]
