# Generated by Django 4.2.6 on 2023-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name_plural': 'favourites'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movies'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_countries',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spoken_languages',
            field=models.TextField(),
        ),
    ]
